project_name: selectel-exporter
builds:
  - env: [CGO_ENABLED=0]
    dir: pkg
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ktshub/selectel-exporter:{{ .Version }}"]
  dockerfile: Dockerfile.goreleaser
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ktsstudio/selectel-exporter
  - --label=org.opencontainers.image.source=https://github.com/ktsstudio/selectel-exporter
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
nfpms:
- maintainer: Alexander Opryshko <hello@kts.studio>
  description: Selectel Exporter
  homepage: https://github.com/ktsstudio/selectel-exporter
  license: Apache-2.0
  formats:
  - deb
  - rpm
  - apk
